name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # 监听 main 分支上的更改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v2

    # 安装 Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    # 生成 Hugo 静态网站
    - name: Build Hugo site
      run: hugo

    # 部署到 gh-pages 分支
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # 指定 Hugo 生成的 public 目录
        publish_branch: gh-pages  # 部署到 gh-pages 分支
